apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-app
spec:
  selector:
    matchLabels:
      app: ebpf-app
  template:
    metadata:
      labels:
        app: ebpf-app
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: ebpf-app
        image: downfa11/ebpf-app # todo
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
        env:
          - name: DEV
            value: "eth0" # host interface
        ports:
          - containerPort: 8080
            hostPort: 8080
            name: metrics
      restartPolicy: Always