{
 "title": "Custom eBPF Dashboard",
 "panels": [
  {
   "title": "XDP Packet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "xdp_pass_total", "legendFormat": "XDP Pass" },
    { "expr": "xdp_drop_total", "legendFormat": "XDP Drop" }
   ]
  },
  {
   "title": "TCP Connect Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(dst_ip,dst_port)(tcp_connect_total)",
     "legendFormat": "{{dst_ip}}:{{dst_port}}"
    }
   ]
  },
  {
   "title": "TCP Connect by destIP",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(dst_ip)(tcp_connect_total)",
     "legendFormat": "{{dst_ip}}"
    }
   ]
  },
  {
   "title": "Node-to-Node Traffic Flow",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "tcp_connect_total",
     "legendFormat": "{{src_ip}} -> {{dst_ip}}:{{dst_port}}"
    }
   ]
  }
 ]
}